// This file is a part of MarkdownToPdf Library by Tomas Kubec
// Distributed under MIT license - see license.txt
//

namespace Orionsoft.MarkdownToPdfLib.Plugins
{
    /// <summary>
    /// Result returned by a plugin
    /// </summary>
    public class ImagePluginResult
    {
        /// <summary>
        /// should be set only if the plugin action was successfull
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// Error message in case of error. If the plugin just does not support the passed data, it must be left empty.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        ///  filename of a temporary file generated by the plugin. The file is deleted by the library, when not needed anymore
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// Intended width of the generated image/pdf in points
        /// </summary>
        public double Width { get; set; }
    }
}